version: '3.3'

services:
  django:
    build: .
    volumes:
      - .:/server/
    ports:
      - "8000:8000"
    container_name: "Server"
  postgres:
    container_name: pg-2
    ports:
        - '5432:5432'
    environment:
        - POSTGRES_PASSWORD=secret
        - PGDATA=/pgdata
    volumes:
        - '/pgdata:/pgdata'
    image: 'postgres:12.3'