# Generated by Django 3.0.7 on 2020-06-25 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='image',
            field=models.FileField(upload_to='city/04:38:42'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traveller', models.CharField(max_length=50)),
                ('review', models.TextField()),
                ('image', models.FileField(upload_to='reviews/04:38:42')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.City')),
            ],
        ),
    ]
