# Generated by Django 3.0.7 on 2020-06-25 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20200625_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='city/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='city',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='reviews/'),
        ),
    ]
